### ISSUE TITLE
sub-man fails with TLS error when regenerating certificates

### ISSUE THREAD

**Issue by martinpitt** [ptoscano/candlepin-container-unofficial#3]
Originating from https://github.com/cockpit-project/bots/issues/5551, see https://github.com/cockpit-project/bots/pull/5601 . 

Cockpit' services image had regenerated the candlepin container's certificates for a long time: https://github.com/cockpit-project/bots/blob/245270d4df621a526a37546b65f220c5326844e2/images/scripts/services.setup#L124 . This is a bit awkward: having to run `dnf install`, it's not [documented](https://github.com/ptoscano/candlepin-container-unofficial/blob/main/README.md), and [also not necessary](https://github.com/cockpit-project/cockpit/pull/19657). The officially documented host name is `candlepin.local`, and we can use that just fine.

With that, the "full product registration" works fine. This is a run on a standard RHEL 9.4 nightly cloud image:

```sh
# setup candlepin server
podman run -d --name candlepin   -p 8080:8080 -p 8443:8443 --hostname candlepin.local   --pull newer ghcr.io/ptoscano/candlepin-unofficial:latest
podman cp candlepin:/etc/candlepin/certs/candlepin-ca.crt .
cp ./candlepin-ca.crt /etc/rhsm/ca/candlepin-ca.pem
cp ./candlepin-ca.crt /etc/pki/ca-trust/source/anchors/
update-ca-trust
echo '127.0.0.1 candlepin.local' >> /etc/hosts

# wait until it is up
until curl --fail https://candlepin.local:8443/candlepin/status; do sleep 1; done

# set up fake product
rm -f /etc/pki/product-default/*.pem /etc/pki/product/*.pem
mkdir -p /etc/pki/product/
podman cp candlepin:/home/candlepin/devel/candlepin/generated_certs/88888.pem /etc/pki/product/

# subscribe and verify
subscription-manager config --server.hostname candlepin.local   --server.port 8443 --server.prefix /candlepin
subscription-manager register --org=admin --activationkey=awesome_os_pool  --force
subscription-manager attach --auto
subscription-manager list
```

This succeeds, and the last command gives
```
Product Name:   Shared File System Bits (no content)
Product ID:     88888
Version:        1.0
Arch:           ALL
Status:         Subscribed
```

However, you asked for a bug report about the cert regeneration. When doing that:
 
```sh
podman run -d --name candlepin   -p 8080:8080 -p 8443:8443 --hostname services.cockpit.lan   --pull newer ghcr.io/ptoscano/candlepin-unofficial

# regenerate TLS certificate
podman exec -i candlepin systemctl stop tomcat
# used by gen_certs.sh
podman exec -i candlepin dnf --setopt install_weak_deps=False -y install hostname
podman exec -i candlepin /home/candlepin/devel/candlepin/bin/deployment/gen_certs.sh -f --hostname services.cockpit.lan
podman exec -i candlepin systemctl start tomcat

podman cp candlepin:/etc/candlepin/certs/candlepin-ca.crt .
cp ./candlepin-ca.crt /etc/rhsm/ca/candlepin-ca.pem
cp ./candlepin-ca.crt /etc/pki/ca-trust/source/anchors/
update-ca-trust
echo '127.0.0.1 services.cockpit.lan' >> /etc/hosts

# wait until it is up
until curl --fail https://services.cockpit.lan:8443/candlepin/status; do sleep 1; done

# set up fake product
rm -f /etc/pki/product-default/*.pem /etc/pki/product/*.pem
mkdir -p /etc/pki/product/
podman cp candlepin:/home/candlepin/devel/candlepin/generated_certs/88888.pem /etc/pki/product/
```

... and trying to register:
```
subscription-manager config --server.hostname services.cockpit.lan --server.port 8443 --server.prefix /candlepin
subscription-manager register --org=admin --activationkey=awesome_os_pool  --force
```

the `register` command fails with

> Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.

and that log file says:
```
2023-11-27 10:50:24,262 [ERROR] subscription-manager:2033:MainThread @utils.py:327 - [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1129)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/subscription_manager/utils.py", line 305, in get_server_versions
    status = cp.getStatus()
  File "/usr/lib64/python3.9/site-packages/rhsm/connection.py", line 2070, in getStatus
    return self.conn.request_get(method, description=_("Checking server status"))
  File "/usr/lib64/python3.9/site-packages/rhsm/connection.py", line 1327, in request_get
    result: Dict[str, Any] = self._request(
  File "/usr/lib64/python3.9/site-packages/rhsm/connection.py", line 1130, in _request
    result, response = self._make_request(
  File "/usr/lib64/python3.9/site-packages/rhsm/connection.py", line 1066, in _make_request
    raise NoValidEntitlement(
  File "/usr/lib64/python3.9/site-packages/rhsm/connection.py", line 1021, in _make_request
    conn = self._create_connection(cert_file=cert_file, key_file=key_file)
  File "/usr/lib64/python3.9/site-packages/rhsm/connection.py", line 811, in _create_connection
    conn.connect()
  File "/usr/lib64/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib64/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/usr/lib64/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1129)
```

**Comment by martinpitt** [comment]
Our services image had been stuck (mostly on samba, but on other bits as well) for 6 months, so I'm not sure which exact version broke this. 4.2.15-1 works, but it's not 100% comparable as on that services image we didn't specify the `--hostname` option of gen_certs.sh.

Is that script even supposed to be an official API, or did the services image rummage in the container's internal guts with that? As I said, I'd rather [drop it completely](https://github.com/cockpit-project/bots/pull/5601) and make everything simpler.

Thanks!

**Comment by ptoscano** [comment]
I think I found out why it does not work: before candlepin 4.3.7, the `gen_certs.sh` script used to also install automatically the generated CA in the system store (i.e. `/etc/pki/ca-trust/source/anchors`); starting from that version, the default behaviour is changed to not do that, with the `-t`/`--trust` option to be used to mimick the old behaviour.

I tried calling `gen_certs.sh` with `-t`/`--trust`, and things work again for me. Would you please check if that works for you as well?

**Comment by martinpitt** [comment]
With `--trust` it does work indeed. Thanks!
